/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: albert_buscio (https://sketchfab.com/albert_buscio)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ps1-style-low-poly-moon-a0800eda5580488092cbb48c415180a9
Title: PS1 style low poly Moon
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import moonScene from '../assets/3d_models/moon.glb'

const Moon = ({moonAnime, ...props}) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(moonScene)
  const { actions } = useAnimations(animations, group)

  useEffect( ()=> {
    Object.values(actions).forEach((action) => action.stop());

    if (actions[moonAnime]) {
        actions[moonAnime].play()
    }

  }, [actions, moonAnime]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Low_Poly_Moonfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="moon" rotation={[-Math.PI / 2, 0, 0.329]} scale={100}>
                  <mesh
                    name="moon_Moon_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.moon_Moon_0.geometry}
                    material={materials.Moon}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

export default Moon
