/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: P3TroV (https://sketchfab.com/P3TroV)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sun-animated-test-8c3ebc78ec014042a61144f46c6f13fa
Title: Sun animated test
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import sunScene from '../assets/3d_models/sun.glb'
import { useFrame } from '@react-three/fiber'

const Sun = ({sunAnime, ...props}) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(sunScene)
  const { actions } = useAnimations(animations, group)

 useFrame( ()=> {
  if(group.current){
    group.current.rotation.y += 0.01;
  }
 });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.022}>
          <group name="23c71f95b90948a0bb8746260230a45efbx" rotation={[-Math.PI, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="GeoSphere001">
                  <mesh
                    name="GeoSphere001_01_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['GeoSphere001_01_-_Default_0'].geometry}
                    material={materials['01_-_Default']}
                  />
                </group>
                <group name="GeoSphere002" scale={0.964}>
                  <mesh
                    name="0"
                    castShadow
                    receiveShadow
                    geometry={nodes['0'].geometry}
                    material={materials['02_-_Default']}
                    morphTargetDictionary={nodes['0'].morphTargetDictionary}
                    morphTargetInfluences={nodes['0'].morphTargetInfluences}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

export default Sun
